-- AlterTable
ALTER TABLE `resident_statistics` MODIFY `resident_type` ENUM('GENDER', 'PERNIKAHAN', 'AGAMA', 'USIA', 'KEPALA_KELUARGA', 'PERKERJAAN', 'PENDIDIKAN', 'WAJIB_PILIH', 'DUSUN', 'ANAK_ANAK') NOT NULL;
